language: go

os:
  - linux
  - osx

go:
  - tip
  - 1.8
  - 1.7

matrix:
  allow_failures:
    - go: tip

before_install:
  - go get -t -v ./...

script:
  - go test -coverprofile=encoding.cov github.com/cstockton/go-trace/encoding
  - go test -coverprofile=trace.cov github.com/cstockton/go-trace

after_success:
  - bash <(curl -s https://codecov.io/bash) -f "*.cov"
