language: go

go:
  - 1.7.4
  - tip

os:
  - linux
  - osx

before_install:
  - go get -t -v ./...

script:
  - go test -coverprofile=encoding.cov github.com/cstockton/go-trace/encoding

after_success:
  - bash <(curl -s https://codecov.io/bash) -f encoding.cov
